/* eslint-disable import/group-exports */

export function isEns(str: string | undefined): str is `${string}.eth` {
  return !!str?.match(/^[a-zA-Z0-9.]+\.eth$/)?.length
}

/**
 * Try to launch the desktop version using the custom protocol `decentraland://position=x,y&realm=zzz`
 * and return a boolean that represents if a loss of focus was detected on the current window
 * (assuming it was due to the interaction generated by the desktop version)
 */
export const launchDesktopApp = async (btnTarget: EventTarget, url: string) => {
  // assume that the desktop version is installed only if
  // we detect a loss of focus on window
  let installed = false
  let isButtonReleased = false

  const handleMouseUp = () => {
    isButtonReleased = true
  }

  const isInstalled = () => {
    installed = true
  }

  window.addEventListener("blur", isInstalled)
  btnTarget.addEventListener("mouseup", handleMouseUp)

  const iframe = document.createElement("iframe")
  iframe.setAttribute("style", "display: none")
  iframe.src = url
  document.body.appendChild(iframe)

  if (!isButtonReleased && (btnTarget as Element).matches(":hover")) {
    isInstalled()
  }

  // wait half of a second to detect the loss of focus because
  // the time it takes for the `blur` event to be fired varies
  // depending on the browser
  return new Promise<boolean>((resolve) => {
    setTimeout(() => {
      window.removeEventListener("blur", isInstalled)
      btnTarget.removeEventListener("mouseup", handleMouseUp)
      document.body.removeChild(iframe)

      resolve(installed)
    }, 500)
  })
}
